package com.medisense.app.domain.model

/**
 * Enumeration of high-level, privacy-safe audit event types.
 *
 * NOTE: These events capture system-level actions for local transparency telemetry.
 * They NEVER contain sensitive medical payloads, symptoms, or medication dosages.
 */
enum class SecurityAuditEventType {
    LOGIN,
    LOGOUT,
    ACCOUNT_SWITCH,
    PROFILE_UPDATED,
    PREDICTION_CREATED,
    PREDICTION_HISTORY_DELETED,
    MEDICATION_CREATED,
    MEDICATION_UPDATED,
    APPOINTMENT_CREATED,
    APPOINTMENT_UPDATED,
    AI_SESSION_STARTED,
    LOCAL_DATA_CLEARED,
    PRIVACY_SETTINGS_CHANGED,
    CLOUD_SYNC,
    DATA_QUALITY_CHECKED,
    HEALTH_REPORT_GENERATED,
    HEALTH_REPORT_EXPORTED,
    HEALTH_REPORT_SHARED,
    CONSULTATION_SUMMARY_GENERATED,
    CONSULTATION_SUMMARY_EXPORTED,
    CONSULTATION_SUMMARY_SHARED,
    EMERGENCY_CARD_VIEWED,
    EMERGENCY_CARD_SHARED,
    EMERGENCY_CONTACT_DIAL_INITIATED,
    DECISION_TRACE_VIEWED,
    DECISION_TRACE_EXPORTED,
    HEALTH_DATA_SHARE_PREPARED,
    HEALTH_DATA_SHARE_CONSENTED,
    HEALTH_DATA_SHARE_EXPORTED,
    HEALTH_DATA_SHARE_REVOKED,
    HEALTH_DATA_SHARE_CANCELLED
}


